### ISSUE TITLE
if y=x, then it takes ages to train

### ISSUE THREAD

**Issue by qingzma** [cjekel/piecewise_linear_fit_py#15]
If independent variable x and dependent variable y=f(x) is the same, in other words, y=f(x)=x.
Then the training process takes ages to train...

```
differential_evolution step 1: f(x)= 2.08676e-23
differential_evolution step 2: f(x)= 2.08676e-23
differential_evolution step 3: f(x)= 2.08676e-23
differential_evolution step 4: f(x)= 2.08103e-23
differential_evolution step 5: f(x)= 2.08103e-23
.....
.....
.....
differential_evolution step 990: f(x)= 2.02263e-25
differential_evolution step 991: f(x)= 2.02263e-25
differential_evolution step 992: f(x)= 2.02263e-25
differential_evolution step 993: f(x)= 2.02263e-25
differential_evolution step 994: f(x)= 2.02263e-25
differential_evolution step 995: f(x)= 2.02263e-25
differential_evolution step 996: f(x)= 2.02263e-25
differential_evolution step 997: f(x)= 2.02263e-25
differential_evolution step 998: f(x)= 2.02263e-25
```

So such circumstances should be avoided?

**Comment by V-Kh** [comment]
Could you provide a little bit more detailed code for us to reproduce your results?

**Comment by qingzma** [comment]
I know it is expected that it will take a long time to train, as pwlf is not needed for such circumstances.
(y=x is the only needed curve, so pwlf fails to find the segment points for each sub-range.)

But shouldn't such circumstances be avoided?

Below is a simple example.

```
import pwlf
X=range(1000)
y=range(1000)
reg = pwlf.PiecewiseLinFit(X, y)
reg.fit(10, disp=True)
```

Thanks in advance.

**Comment by cjekel** [comment]
Hey this is a very good point that I'm glad you've brought up! Also thanks for the very easily reproducible code!

When you provide the keyword ```disp=True``` it overrides my defaults for scipy ```differential_evolution``` in favor of the standard defaults for ```differential_evolution```. My idea was that an advanced user would be able to specify Differential Evolution parameters useful for  their specific problem.

**I understand the confusion since this isn't properly documented in the docstring, and the explicit or implicit nature of this is not made clear.**

Let's just see what happens here.

Input:
```
import pwlf
X=range(1000)
y=range(1000)
reg = pwlf.PiecewiseLinFit(X,  y, disp_res=True)
reg.fit(10, disp=True)
```
Output:
```
     fun: 1.7971894951976369e-25
 message: 'Optimization terminated successfully.'
    nfev: 12835
     nit: 94
 success: True
       x: array([  1.325686  ,   1.52128594, 301.43600289, 371.79944721,
         6.03377724, 515.81553819,  59.76723296, 922.55499426,
       995.28519781])
```
Notice how the optimization got stuck minimizing noise in double precision? Also notice 12,835 function evaluations and 94 iterations. 

Now let's try the optimization again with my ```differential_evolution``` defaults.
```
reg.fit(10)
```
Output:
```
     fun: 2.3741168116426143e-24
 message: 'Optimization terminated successfully.'
    nfev: 910
     nit: 1
 success: True
       x: array([448.68322799, 615.82045751, 443.11519005, 613.19074307,
       994.14519401,   3.9514902 , 480.25537288,  71.3368196 ,
        58.06916446])
```
Notice how the optimization algorithm completed in one iteration with only 910 function evalutions?

The keywords you are missing are related to convergence. Let me just show what these keywords mean from the [differential evolution documentation](https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.optimize.differential_evolution.html).

```
    tol : float, optional
        Relative tolerance for convergence, the solving stops when
        ``np.std(pop) <= atol + tol * np.abs(np.mean(population_energies))``,
        where and `atol` and `tol` are the absolute and relative tolerance
        respectively.
    atol : float, optional
        Absolute tolerance for convergence, the solving stops when
        ``np.std(pop) <= atol + tol * np.abs(np.mean(population_energies))``,
        where and `atol` and `tol` are the absolute and relative tolerance
        respectively.
```

So let's try again with an absolute tolerance specified.
```
reg.fit(10, disp=True, atol=1e-15)
```
Output:
```
differential_evolution step 1: f(x)= 2.37491e-24
     fun: 2.3749146843729234e-24
 message: 'Optimization terminated successfully.'
    nfev: 280
     nit: 1
 success: True
       x: array([297.62163922, 487.19057852, 854.29934663,   4.07624417,
       451.53546909, 645.20973533, 789.49520917,  93.89835081,
       773.69384477])
```

And now the optimization finishes in one iteration because our objective function is lower than our absolute tolerance. 

Does this help clarify what's going on?

**Comment by qingzma** [comment]
Wow, that is very clear.
Thanks so much for the help.
